// <auto-generated />
namespace Tehnika.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGrading : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGrading));
        
        string IMigrationMetadata.Id
        {
            get { return "202201160344002_AddGrading"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
